spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
server:
  servlet:
    context-path: /hr
  port: 8080
mybatis:
  type-aliases-package: cn.bdqn.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    auto-mapping-behavior: full

